
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-for-minio
  labels:
    type: local
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/minio
