apiVersion: v1
kind: PersistentVolume
metadata:
  name: subscriptions-holder-pv-for-pg
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/subscriptions-holder-db/postgresql
