apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
stringData:
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094" # 2 for ui and compose
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093,1@localhost:9093" # 2 for ui and compose
  KAFKA_CFG_NODE_ID: "1"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_KRAFT_CLUSTER_ID: L0ZEQh1yTbGhNNUE7-6wSQ
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_ADVERTISED_HOST_NAME: kafka