ARG BUILD_HOME=/app

FROM gradle:9.2.1-jdk21-jammy AS build
#FROM  --platform=linux/arm64 gradle:8.6.0-jdk17

ARG PROTOBUF_SUBMODULE=protobuf_schemas
ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME
WORKDIR $APP_HOME

ARG SERVICE_NAME=kafka_message_consumer

COPY ./gradle ./gradle
COPY ./build.gradle ./settings.gradle ./gradlew ./
COPY ./buildSrc ./buildSrc
COPY ./$SERVICE_NAME ./$SERVICE_NAME
COPY ./$PROTOBUF_SUBMODULE ./$PROTOBUF_SUBMODULE

RUN ["/bin/bash", "-c", "gradle clean bootJar -x test"]

FROM eclipse-temurin:21.0.2_13-jre-alpine
LABEL authors="turtality"

ARG TZ=Europe/Moscow
ENV TZ=${TZ}

ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME
WORKDIR $BUILD_HOME

ENV SERVICE_NAME=kafka_message_consumer
ARG JAR_VERSION
ENV ENV_JAR_VERSION=$JAR_VERSION
ENV ENV_PATH_BUILD_JAR=$APP_HOME/$SERVICE_NAME/build/libs/$SERVICE_NAME-$JAR_VERSION.jar
ENV ENV_PATH_TO_JAR=$SERVICE_NAME-$JAR_VERSION.jar
ARG JVM_PARAMS=""

RUN echo "$TZ" > /etc/timezone

COPY --from=build ./$ENV_PATH_BUILD_JAR ./

CMD java ${JVM_PARAMS} -jar ${ENV_PATH_TO_JAR}