FROM eclipse-temurin:21.0.2_13-jdk-jammy AS build
#FROM  --platform=linux/arm64 gradle:8.6.0-jdk17

ARG SERVICE_NAME=kafka_message_consumer

COPY ./gradle ./gradle
COPY ./build.gradle ./settings.gradle ./gradlew ./
COPY ./buildSrc ./buildSrc
COPY ./$SERVICE_NAME ./$SERVICE_NAME

RUN ["/bin/bash", "-c", "./gradlew clean bootJar -x test"]

FROM eclipse-temurin:21.0.2_13-jre-alpine
LABEL authors="turtality"

ARG TZ=Europe/Moscow
ENV TZ ${TZ}

ENV SERVICE_NAME=kafka_message_consumer
ARG JAR_VERSION
ENV ENV_JAR_VERSION $JAR_VERSION
ENV ENV_PATH_BUILD_JAR=$SERVICE_NAME/build/libs/$SERVICE_NAME-$JAR_VERSION.jar
ENV ENV_PATH_TO_JAR=$SERVICE_NAME-$JAR_VERSION.jar

RUN echo "$TZ" > /etc/timezone

WORKDIR /app

COPY --from=build ./$ENV_PATH_BUILD_JAR ./

ENTRYPOINT java -Xms400m -Xmx400m \
             -XX:MaxMetaspaceSize=150m \
             -XX:NewSize=150m \
             -XX:MaxNewSize=150m \
             -XX:+UseG1GC \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:HeapDumpPath=./dump.hprof \
             -XX:+UseGCOverheadLimit \
             -XX:+UseStringDeduplication \
             -Xlog:gc=info:file=./gc-%p-%t.log:tags,uptime,time,level:filecount=5,filesize=10m \
             -jar "$ENV_PATH_TO_JAR"