FROM  --platform=linux/arm64 gradle:8.2.1-jdk17
LABEL authors="turtality"

ARG JAR_VERSION
ENV ENV_JAR_VERSION $JAR_VERSION

ENV ENV_PATH_TO_JAR=t_coubs_initiator/build/libs/t_coubs_initiator-$JAR_VERSION.jar

WORKDIR /app
COPY ./t_coubs_initiator/src ./t_coubs_initiator/src
COPY ./t_coubs_initiator/build.gradle ./t_coubs_initiator/
COPY ./build.gradle ./
COPY ./settings.gradle ./

RUN ["/bin/bash", "-c", "gradle clean bootJar -x test"] # not alpine

ENTRYPOINT java -jar $ENV_PATH_TO_JAR