FROM  --platform=linux/arm64 gradle:8.2.1-jdk17
LABEL authors="turtality"

ARG JAR_VERSION
ENV ENV_JAR_VERSION $JAR_VERSION

ENV ENV_PATH_TO_JAR=coub_tags_searcher/build/libs/coub_tags_searcher-$JAR_VERSION.jar

WORKDIR /app
COPY ./coub_tags_searcher/src ./coub_tags_searcher/src
COPY ./coub_tags_searcher/build.gradle ./coub_tags_searcher/
COPY ./build.gradle ./
COPY ./settings.gradle ./

RUN ["/bin/bash", "-c", "gradle clean bootJar -x test"] # not alpine

ENTRYPOINT java -jar $ENV_PATH_TO_JAR