FROM  --platform=linux/arm64 gradle:8.2.1-jdk17
LABEL authors="turtality"

ARG JAR_VERSION
ENV ENV_JAR_VERSION $JAR_VERSION

ENV ENV_PATH_TO_JAR=spring_eureka_registry/build/libs/spring_eureka_registry-$JAR_VERSION.jar

WORKDIR /app
COPY ./spring_eureka_registry/src ./spring_eureka_registry/src
COPY ./spring_eureka_registry/build.gradle ./spring_eureka_registry/
COPY ./build.gradle ./
COPY ./settings.gradle ./

RUN ["/bin/bash", "-c", "gradle clean bootJar -x test"] # not alpine

ENTRYPOINT java -jar $ENV_PATH_TO_JAR