FROM  --platform=linux/arm64 gradle:8.2.1-jdk17
LABEL authors="turtality"

ARG JAR_VERSION
ENV ENV_JAR_VERSION $JAR_VERSION

ENV ENV_PATH_TO_JAR=kafka_message_consumer/build/libs/kafka_message_consumer-$JAR_VERSION.jar

WORKDIR /app
COPY ./kafka_message_consumer/src ./kafka_message_consumer/src
COPY ./kafka_message_consumer/build.gradle ./kafka_message_consumer/
COPY ./build.gradle ./
COPY ./settings.gradle ./

RUN ["/bin/bash", "-c", "gradle clean bootJar -x test"] # not alpine

ENTRYPOINT java -jar $ENV_PATH_TO_JAR