ARG BUILD_HOME=/app

FROM --platform=$BUILDPLATFORM gradle:9.8.0-jdk21-jammy AS build
#FROM  --platform=linux/arm64 gradle:8.6.0-jdk17

ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME
WORKDIR $APP_HOME
ENV GRADLE_USER_HOME=/app/.gradle

ARG SERVICE_NAME=kafka_message_producer

# 1. Copy everything except ignored in .dockerignore
COPY . ./

# 2. Download dependencies for everything (cached, unless build-files and buildSrc has not changed)
RUN --mount=type=cache,id=gradle-cache,target=/app/.gradle \
    gradle dependencies --no-daemon

# 4. Build JAR
RUN --mount=type=cache,id=gradle-cache,target=/app/.gradle \
    gradle :$SERVICE_NAME:bootJar -x test

FROM eclipse-temurin:21.0.2_13-jre-alpine
LABEL authors="turtality"

ARG TZ=Europe/Moscow
ENV TZ=${TZ}

ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME
WORKDIR $BUILD_HOME

ENV SERVICE_NAME=kafka_message_producer
ARG JAR_VERSION
ENV ENV_JAR_VERSION=$JAR_VERSION
ENV ENV_PATH_BUILD_JAR=$APP_HOME/$SERVICE_NAME/build/libs/$SERVICE_NAME-$JAR_VERSION.jar
ENV ENV_PATH_TO_JAR=$SERVICE_NAME-$JAR_VERSION.jar
ARG JVM_PARAMS=""

RUN echo "$TZ" > /etc/timezone

COPY --from=build ./$ENV_PATH_BUILD_JAR ./

CMD java ${JVM_PARAMS} -jar ${ENV_PATH_TO_JAR}