ARG BUILD_HOME=/app

FROM gradle:8.7.0-jdk21-jammy AS build
#FROM  --platform=linux/arm64 gradle:8.6.0-jdk17

ARG SERVICE_NAME=telegram_chat_service
ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME
WORKDIR $APP_HOME

COPY ./gradle ./gradle
COPY ./build.gradle ./settings.gradle ./gradlew ./
COPY ./buildSrc ./buildSrc
COPY ./$SERVICE_NAME ./$SERVICE_NAME

RUN ["/bin/bash", "-c", "gradle clean bootJar -x test"]

FROM eclipse-temurin:21.0.2_13-jre-alpine
LABEL authors="turtality"

ARG TZ=Europe/Moscow
ENV TZ=${TZ}

ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME
WORKDIR $BUILD_HOME

ENV SERVICE_NAME=telegram_chat_service
ARG JAR_VERSION
ENV ENV_JAR_VERSION=$JAR_VERSION
ENV ENV_PATH_BUILD_JAR=$APP_HOME/$SERVICE_NAME/build/libs/$SERVICE_NAME-$JAR_VERSION.jar
ENV ENV_PATH_TO_JAR=$SERVICE_NAME-$JAR_VERSION.jar
ARG TELEGRAM_CHAT_SERVICE_JASYPT_PARAMS=""
ARG JVM_PARAMS=""

RUN echo "$TZ" > /etc/timezone && apk --no-cache add curl

COPY --from=build ./$ENV_PATH_BUILD_JAR ./

# entrypoint не работает с шеллом, работает только ARG переменные
# не работает с переменными вообще. нужно использовать голый entrypoint
CMD java ${TELEGRAM_CHAT_SERVICE_JASYPT_PARAMS} ${JVM_PARAMS} -jar ${ENV_PATH_TO_JAR}