application:
  bot:
    name: #name
    token: #token
  templates:
    dir: "/freemarker/templates"


spring:
  application:
    name: telegram_bot

server:
  port: 8084


logging:
  level:
    root: INFO

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true

debug: false

