application:
  kafka:
    topic:
      community_subscription: "coub-com-sub"
      tag_subscription: "coub-tag-sub"
    producers:
      community-coubs:
        client-id: "community-coubs-producer" # custom props configuration in factory
      tag-coubs:
        client-id: "tag-coubs-producer" # custom props configuration in factory



spring:
  application:
    name: kafka-message-producer
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:127.0.0.1:9092} # common bootstrap server for every producer
    producer:
      client-id: "coub-producer"
      retries: 5


server:
  port: 8083


logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
  zipkin:
    tracing:
      connect-timeout: 1s
      read-timeout: 10s
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}

  tracing:
    sampling:
      probability: 1.0


#debug: true

