#!/bin/bash

## Two step helm release of the jforwarder chart, mirroring the old
## release.sh (substitute the image) + apply-all.sh (apply it) split:
##
##   ./release.sh version -u dankoy -t 1.9.6     # writes values-release.yaml
##   ./release.sh install -f values-secrets.yaml # helm upgrade --install

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="${SCRIPT_DIR}/jforwarder"
VALUES_FILE="${SCRIPT_DIR}/values-release.yaml"

Help() {
  echo "Releases the jforwarder helm chart in two steps"
  echo
  echo "Syntax: release.sh <command> [options]"
  echo
  echo "commands:"
  echo "  version   Write the image coordinates into values-release.yaml."
  echo "            Nothing is sent to the cluster."
  echo "  install   Install or upgrade the release with values-release.yaml."
  echo
  echo "version options:"
  echo "  -u  Docker registry user. Required."
  echo "  -t  Image tag. Required."
  echo "  -H  Registry domain. Default: docker.io"
  echo "  -h  Print this help."
  echo
  echo "install options:"
  echo "  -n  Kubernetes namespace. Default: jforwarder"
  echo "  -r  Helm release name. Default: jforwarder"
  echo "  -f  Extra values file, repeatable. Use it for the real secrets."
  echo "  -d  Dry run, renders the manifests without touching the cluster."
  echo "  -h  Print this help."
  echo
  echo "Example:"
  echo "  ./release.sh version -u dankoy -t 1.9.6"
  echo "  ./release.sh install -f values-secrets.yaml"
}

### version: substitute the image coordinates ################################

cmd_version() {
  local user="" tag="" registry="docker.io"

  OPTIND=1
  while getopts ":u:t:H:h" opt; do
    case ${opt} in
      h) Help; exit 0 ;;
      u) user=${OPTARG} ;;
      t) tag=${OPTARG} ;;
      H) registry=${OPTARG} ;;
      :) printf "Option -%s requires an argument.\n" "${OPTARG}"; exit 1 ;;
      ?) printf "Invalid option: -%s.\n" "${OPTARG}"; exit 1 ;;
    esac
  done

  if [ -z "${tag}" ] || [ -z "${user}" ]; then
    echo 'Missing -t and -u' >&2
    Help
    exit 1
  fi

  cat > "${VALUES_FILE}" <<EOF
# Generated by release.sh version -u ${user} -t ${tag} -H ${registry}
# Applied by "release.sh install". Do not edit and do not commit it.
image:
  registry: ${registry}
  user: ${user}
  tag: ${tag}
EOF

  printf "\nWrote %s\n registry: %s\n user: %s\n tag: %s\n\n" \
    "${VALUES_FILE}" "${registry}" "${user}" "${tag}"
}

### install: apply the chart #################################################

cmd_install() {
  local namespace="jforwarder" release="jforwarder" dry_run=""
  local values_files=()

  OPTIND=1
  while getopts ":n:r:f:dh" opt; do
    case ${opt} in
      h) Help; exit 0 ;;
      n) namespace=${OPTARG} ;;
      r) release=${OPTARG} ;;
      f) values_files+=("${OPTARG}") ;;
      d) dry_run="--dry-run" ;;
      :) printf "Option -%s requires an argument.\n" "${OPTARG}"; exit 1 ;;
      ?) printf "Invalid option: -%s.\n" "${OPTARG}"; exit 1 ;;
    esac
  done

  if [ ! -f "${VALUES_FILE}" ]; then
    echo "${VALUES_FILE} not found, run 'release.sh version -u <user> -t <tag>' first" >&2
    exit 1
  fi

  printf "\nReleasing %s\n namespace: %s\n values: %s\n\n" \
    "${release}" "${namespace}" "${VALUES_FILE}"

  local helm_args=(upgrade --install "${release}" "${CHART_DIR}"
    --namespace "${namespace}"
    --create-namespace
    -f "${VALUES_FILE}")

  # bash 3.2 (default on macos) treats an empty array as unset under `set -u`
  for file in ${values_files[@]+"${values_files[@]}"}; do
    helm_args+=(-f "${file}")
  done

  if [ -n "${dry_run}" ]; then
    helm_args+=("${dry_run}")
  fi

  helm "${helm_args[@]}"
}

### dispatch #################################################################

COMMAND="${1:-}"
if [ $# -gt 0 ]; then
  shift
fi

case "${COMMAND}" in
  version) cmd_version "$@" ;;
  install) cmd_install "$@" ;;
  -h|--help|help) Help; exit 0 ;;
  "") echo "Missing command" >&2; Help; exit 1 ;;
  *) printf "Unknown command: %s\n\n" "${COMMAND}" >&2; Help; exit 1 ;;
esac
