spring:
  application:
    name: coub-connector


server:
  port: 8081

coub:
  connector:
    url: "https://coub.com/"
    apiUrl: "https://coub.com/api/v2/"


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          openfeign: DEBUG


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true

feign:
  client:
    config:
      default:
        loggerLevel: basic

