{{- if .Values.secrets.create }}
{{- range $name, $data := .Values.secrets.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "jforwarder.componentLabels" (dict "root" $ "component" "secret") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
