version: "3.9"

services:

  prometheus-node-exporter:
    image: prom/node-exporter:latest
    container_name: prometheus-node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - jforwarder-network

  grafana:
    env_file:
      - .env
    image: 'grafana/grafana:latest'
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_volume:/var/lib/grafana
      - './Dashboard.yml:/etc/grafana/provisioning/dashboards/Dashboard.yml'
      - './4701_rev10.json:/etc/grafana/provisioning/dashboards/4701_rev10.json'
      - './9628_rev7.json:/etc/grafana/provisioning/dashboards/9628_rev7.json'
      - './1860_rev31.json:/etc/grafana/provisioning/dashboards/1860_rev31.json'
      - './Datasource.yml:/etc/grafana/provisioning/datasources/Datasource.yml'
    networks:
      - jforwarder-network

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/config.yml'
      - prometheus_volume:/prometheus
    networks:
      - jforwarder-network

  prometheus-postgres-exporter:
    env_file:
      - .env
    image: 'bitnami/postgres-exporter:latest'
    container_name: prometheus-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
    networks:
      - jforwarder-network

volumes:
  prometheus_volume:
    driver: local
  grafana_volume:
    driver: local

networks:
  jforwarder-network:
    name: jforwarder-network
    external: true
