/*
 * This file is generated by jOOQ.
 */
package ru.dankoy.telegramchatservice.core.domain.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long chatId;
    private String type;
    private String title;
    private String firstName;
    private String lastName;
    private String username;
    private Boolean active;
    private Integer messageThreadId;
    private LocalDateTime dateCreated;
    private LocalDateTime dateModified;

    public Chats() {}

    public Chats(Chats value) {
        this.id = value.id;
        this.chatId = value.chatId;
        this.type = value.type;
        this.title = value.title;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.username = value.username;
        this.active = value.active;
        this.messageThreadId = value.messageThreadId;
        this.dateCreated = value.dateCreated;
        this.dateModified = value.dateModified;
    }

    public Chats(
        Long id,
        Long chatId,
        String type,
        String title,
        String firstName,
        String lastName,
        String username,
        Boolean active,
        Integer messageThreadId,
        LocalDateTime dateCreated,
        LocalDateTime dateModified
    ) {
        this.id = id;
        this.chatId = chatId;
        this.type = type;
        this.title = title;
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.active = active;
        this.messageThreadId = messageThreadId;
        this.dateCreated = dateCreated;
        this.dateModified = dateModified;
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.chats.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.chats.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.chats.chat_id</code>.
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.chats.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.chats.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.chats.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.chats.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.chats.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.chats.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>public.chats.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.chats.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>public.chats.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.chats.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>public.chats.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.chats.active</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * Getter for <code>public.chats.message_thread_id</code>.
     */
    public Integer getMessageThreadId() {
        return this.messageThreadId;
    }

    /**
     * Setter for <code>public.chats.message_thread_id</code>.
     */
    public void setMessageThreadId(Integer messageThreadId) {
        this.messageThreadId = messageThreadId;
    }

    /**
     * Getter for <code>public.chats.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Setter for <code>public.chats.date_created</code>.
     */
    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * Getter for <code>public.chats.date_modified</code>.
     */
    public LocalDateTime getDateModified() {
        return this.dateModified;
    }

    /**
     * Setter for <code>public.chats.date_modified</code>.
     */
    public void setDateModified(LocalDateTime dateModified) {
        this.dateModified = dateModified;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Chats other = (Chats) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.messageThreadId == null) {
            if (other.messageThreadId != null)
                return false;
        }
        else if (!this.messageThreadId.equals(other.messageThreadId))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.dateModified == null) {
            if (other.dateModified != null)
                return false;
        }
        else if (!this.dateModified.equals(other.dateModified))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.messageThreadId == null) ? 0 : this.messageThreadId.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.dateModified == null) ? 0 : this.dateModified.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(id);
        sb.append(", ").append(chatId);
        sb.append(", ").append(type);
        sb.append(", ").append(title);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(username);
        sb.append(", ").append(active);
        sb.append(", ").append(messageThreadId);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(dateModified);

        sb.append(")");
        return sb.toString();
    }
}
