spring:
  application:
    name: spring-eureka-registry

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true