spring:
  application:
    name: spring-eureka-registry

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false

  server:
    expected-client-renewal-interval-seconds: 3
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
    registry-sync-retries: 3
    max-threads-for-peer-replication: 5
    wait-time-in-ms-when-sync-empty: 5
  instance:
    lease-expiration-duration-in-seconds: 90

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true

  # For Exemplars to work we need histogram buckets
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"