apiVersion: v1
kind: Secret
metadata:
  name: telegram-chat-service-secret
type: Opaque
stringData:
  TELEGRAM_CHAT_SERVICE_POSTGRES_CONTAINER_URL: "jdbc:postgresql://host:5432/db"
  TELEGRAM_CHAT_SERVICE_POSTGRES_CONTAINER_USER: "user"
  TELEGRAM_CHAT_SERVICE_POSTGRES_CONTAINER_PASSWORD: "pass"
  TELEGRAM_CHAT_SERVICE_POSTGRES_CONTAINER_DB: "db"
  TELEGRAM_CHAT_SERVICE_JASYPT_MASTER_PASSWORD: "pass2"
  TELEGRAM_CHAT_SERVICE_JASYPT_PARAMS: |
        -Djasypt.encryptor.password=${TELEGRAM_CHAT_SERVICE_JASYPT_MASTER_PASSWORD}
        -Djasypt.encryptor.algorithm=PBEWithMD5AndDES
        -Djasypt.encryptor.ivGeneratorClassName=org.jasypt.iv.NoIvGenerator