 apiVersion: monitoring.coreos.com/v1alpha1
 kind: AlertmanagerConfig
 metadata:
    name: alert-config-telegram
    # namespace: monitoring
    labels:
      app: kube-prometheus-stack
      app.kubernetes.io/instance: kube-prometheus-stack
      release: prometheus-kube-stack # the release label should be the exact label of the prometheus helm release label
      alertmanagerConfig: alertmanager-telegram # custom label and also set this label to alertmanager in the prometheus-stack values.yaml
 spec:
   route:
     groupBy: ["job", "alertname", "namespace"]
     groupWait: 30s
     groupInterval: 5m
     repeatInterval: 1m
     receiver: "telegram-receiver"
     routes:
       - receiver: "telegram-receiver"
         continue: true
   receivers:
    - name: 'telegram-receiver'
      telegramConfigs:
        - botToken:
            name: telegram-bot-token-secret # refer to the secret name has been created before
            key: bot-token # bot-token data in the secret
          chatID: 123
          parseMode: 'HTML' # The template I provide is in Markdown Mode
          disableNotifications: false
          sendResolved: true
      