apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: my-cluster
servers: 1
agents: 0
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  hostIP: "127.0.0.1" # where the Kubernetes API will be listening on
  hostPort: "6445" # where the Kubernetes API listening port will be mapped to on your host system
ports:
  - port: 8443:443
    nodeFilters:
      - loadbalancer
  - port: 8080:80
    nodeFilters:
      - loadbalancer
volumes: # repeatable flags are represented as YAML lists
  # default volumes are in /var/lib/rancher/k3s/storage@all
  # - volume: /var/volumes:/var/lib/rancher/k3s/storage@all # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
  #   nodeFilters:
  #     - server:0
  #     - agent:*
  - volume: /var/volumes:/data # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
    nodeFilters:
      - server:0
      - agent:*

