apiVersion: v1
kind: PersistentVolume
metadata:
  name: zipkin-cassandra-pv
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/zipkin-cassandra/cassandra
