/*
 * This file is generated by jOOQ.
 */
package ru.dankoy.telegramchatservice.core.domain.jooq;

import ru.dankoy.telegramchatservice.core.domain.jooq.tables.Chats;

/** Convenience access to all tables in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

  /** The table <code>public.chats</code>. */
  public static final Chats CHATS = Chats.CHATS;
}
