apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:

# Deprecated. Moved to mimir backed metrics.
  # - id: prometheus
  #   uid: prometheus
  #   type: prometheus
  #   name: Prometheus
  #   editable: true                        # whether it should be editable
  #   isDefault: false                      # whether this should be the default DS
  #   org_id: 1                             # id of the organization to tie this datasource to
  #   access: proxy
  #   url: "http://prometheus:9090"
  #   version: 2                            # well, versioning

# Added header to differentiate prometheus client. Prometheus scraps all data and pushes it 
# to mimir with tenant "jforwarder". So all "jforwarder" related stuff should be accessed with its header.
  - id: prometheus
    uid: prometheus
    type: prometheus
    name: Prometheus
    editable: true                        # whether it should be editable
    isDefault: true                      # whether this should be the default DS
    org_id: 1                             # id of the organization to tie this datasource to
    access: proxy
    url: "http://grafana-mimir:9009/prometheus"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "jforwarder"
    version: 1                            # well, versioning

#  - id: Tempo
#    name: Tempo
#    type: tempo
#    access: proxy
#    orgId: 1
#    url: http://grafana-tempo:3200
#    basicAuth: false
#    isDefault: false
#    version: 1
#    editable: false
#    apiVersion: 1
#    uid: tempo
#    jsonData:
#      httpMethod: GET
#      tracesToLogs:
#        datasourceUid: 'loki'
#
  - id: Loki
    name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://grafana-loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
#    jsonData:
#      derivedFields:
#        - datasourceUid: tempo
#          matcherRegex: \[.+,(.+?),
#          name: traceID
#          url: $${__value.raw}