rules:
  unpinned-uses:
    ignore:
      - super-linter.yml
      - codeql-advanced.yml
      - publish.yml
      - super-linter.yml
      - rebase_dependencies.yml
      - test.yml
  template-injection:
    ignore:
      - publish.yml
      - test.yml