apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry-app
  labels:
    app: kafka-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
        - image: "docker.io/confluentinc/cp-schema-registry:7.9.0"
          name: kafka-schema-registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
          - configMapRef:
              name: kafka-schema-registry-config
          - secretRef:
              name: kafka-schema-registry-secret
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 350Mi