apiVersion: v1
kind: Secret
metadata:
  name: kafka-schema-registry-secret
type: Opaque
stringData:
  KAFKA_SERVER: my-cluster-kafka-bootstrap:9092
  SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
  SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: full
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://my-cluster-kafka-bootstrap:9092
  SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://my-cluster-kafka-brokers:9092
  SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081