apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  labels:
    app: kafka-schema-registry-service
spec:
  type: NodePort
  selector:
    app: kafka-schema-registry
  ports:
    - port: 8081
      targetPort: 8081