apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-app
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - image: "docker.io/provectuslabs/kafka-ui:v0.7.2"
          name: kafka-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: kafka-ui-config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
