application:
  kafka:
    schema-registry:
      url: ${SCHEMA_REGISTRY:http://localhost:9081}
    topic:
      coub-com-subs: "coub-com-sub"
      coub-tag-subs: "coub-tag-sub"
      coub-channel-subs: "coub-channel-sub"
    consumers:
      community-coubs-consumer:
        group-id: "community-coubs-consumer-group"
        client-id: "community-coubs-consumer-id" # custom props configuration in factory
      tag-coubs-consumer:
        group-id: "tag-coubs-consumer-group"
        client-id: "tag-coubs-consumer-id" # custom props configuration in factory
      channel-coubs-consumer:
        group-id: "channel-coubs-consumer-group"
        client-id: "channel-coubs-consumer-id"
      community-coubs-consumer-protobuf:
        group-id: "community-coubs-consumer-protobuf-group"
        client-id: "community-coubs-consumer-protobuf-id" # custom props configuration in factory
      tag-coubs-consumer-protobuf:
        group-id: "tag-coubs-consumer-protobuf-group"
        client-id: "tag-coubs-consumer-protobuf-id" # custom props configuration in factory
      channel-coubs-consumer-protobuf:
        group-id: "channel-coubs-consumer-protobuf-group"
        client-id: "channel-coubs-consumer-protobuf-id"
#      coubs-consumer: # for handlers in one listener
#        group-id: "coubs-consumer-group"
#        client-id: "coubs-consumer-id"


spring:
  application:
    name: kafka-message-consumer
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9094}
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:http://localhost:9094}
      client-id: "coubs-consumer" # default one
      group-id: "coubs_group"
    listener:
      ack-mode: batch

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

server:
  port: 8085


logging:
  level:
    root: INFO
    ru:
      dankoy:
        kafkamessageconsumer:
          core:
            feign: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    #    instance-id: "${spring.application.name}:${server.port}"


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
  zipkin:
    tracing:
      connect-timeout: 1s
      read-timeout: 10s
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}

  tracing:
    sampling:
      probability: 1.0

  # For Exemplars to work we need histogram buckets
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

#debug: true

