application:
  kafka:
    topic: "coubs"


spring:
  application:
    name: kafka-message-consumer
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:127.0.0.1:9092}
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:http://127.0.0.1:9092}
      client-id: "coubs-consumer"
      group-id: "coubs_group"
    listener:
      ack-mode: batch


server:
  port: 8085


logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
  zipkin:
    tracing:
      connect-timeout: 1s
      read-timeout: 10s
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}

  tracing:
    sampling:
      probability: 1.0

#debug: true

