apiVersion: v1
kind: Service
metadata:
  name: spring-eureka-registry
  namespace: jforwarder
  labels:
    app: spring-eureka-registry-service
spec:
  type: ClusterIP
  selector:
    app: spring-eureka-registry
  ports:
    - port: 8761
      targetPort: 8761