/*
 * This file is generated by jOOQ.
 */
package ru.dankoy.telegramchatservice.core.domain.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.dankoy.telegramchatservice.core.domain.jooq.tables.Chats;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chats.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chats.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chats.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.chats.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chats.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.chats.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chats.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.chats.first_name</code>.
     */
    public void setFirstName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chats.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.chats.last_name</code>.
     */
    public void setLastName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chats.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.chats.username</code>.
     */
    public void setUsername(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.chats.username</code>.
     */
    public String getUsername() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.chats.active</code>.
     */
    public void setActive(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.chats.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.chats.message_thread_id</code>.
     */
    public void setMessageThreadId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.chats.message_thread_id</code>.
     */
    public Integer getMessageThreadId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.chats.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.chats.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.chats.date_modified</code>.
     */
    public void setDateModified(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.chats.date_modified</code>.
     */
    public LocalDateTime getDateModified() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(Long id, Long chatId, String type, String title, String firstName, String lastName, String username, Boolean active, Integer messageThreadId, LocalDateTime dateCreated, LocalDateTime dateModified) {
        super(Chats.CHATS);

        setId(id);
        setChatId(chatId);
        setType(type);
        setTitle(title);
        setFirstName(firstName);
        setLastName(lastName);
        setUsername(username);
        setActive(active);
        setMessageThreadId(messageThreadId);
        setDateCreated(dateCreated);
        setDateModified(dateModified);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(ru.dankoy.telegramchatservice.core.domain.jooq.tables.pojos.Chats value) {
        super(Chats.CHATS);

        if (value != null) {
            setId(value.getId());
            setChatId(value.getChatId());
            setType(value.getType());
            setTitle(value.getTitle());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setUsername(value.getUsername());
            setActive(value.getActive());
            setMessageThreadId(value.getMessageThreadId());
            setDateCreated(value.getDateCreated());
            setDateModified(value.getDateModified());
            resetChangedOnNotNull();
        }
    }
}
