name: "Check Changes"

on:
  workflow_call:
  # Map the workflow outputs to job outputs
    outputs:
      packages:
        description: "Packages output string"
        value: ${{ jobs.changes.outputs.final }}

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'packages' output variable
      individual: ${{ steps.filter.outputs.changes }}
      all: ${{ steps.all.outputs.all }}
      final: ${{ steps.final.outputs.final }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          subscriptions_holder: 
            - 'subscriptions_holder/**'
          t_coubs_initiator: 
            - 't_coubs_initiator/**'
          coub_smart_searcher: 
            - 'coub_smart_searcher/**'
          kafka_message_producer: 
            - 'kafka_message_producer/**'
          kafka_message_consumer: 
            - 'kafka_message_consumer/**'
          telegram_bot: 
            - 'telegram_bot/**'
          subscriptions_scheduler: 
            - 'subscriptions_scheduler/**'
          buildSrc:
            - 'buildSrc/**'

    - name: if result does not contains buildSrc
      id: individual
      if: ${{ ! contains(steps.filter.outputs.changes, 'buildSrc') }}
      run: echo "individual=${{steps.filter.outputs.changes}} >> $GITHUB_OUTPUT"


    - name: if result contains buildSrc
      id: all
      if: ${{ contains(steps.filter.outputs.changes, 'buildSrc') }}
      run: |
        echo "all=[\"subscriptions_holder\", 
             \"t_coubs_initiator\", 
             \"coub_smart_searcher\", 
             \"kafka_message_producer\", 
             \"kafka_message_consumer\", 
             \"telegram_bot\", 
             \"subscriptions_scheduler\"]"
        >> "$GITHUB_OUTPUT"

    - name: print final version
      id: final
      env:
        INDIVIDUAL: ${{ steps.individual.outputs.individual }}
        ALL: ${{ steps.all.outputs.all }}
      run: |
        if [ -z "${{ steps.individual.outputs.individual }}" ]; then 
          echo "final=${{ steps.all.outputs.all }}" >> $GITHUB_OUTPUT;
        elif [ -z "${{ steps.all.outputs.all }}" ]; then
          echo "final=${{ steps.individual.outputs.individual }}" >> $GITHUB_OUTPUT;
        else
          echo "final=[]" >> $GITHUB_OUTPUT;
        fi
