name: Docker build using matrix

on:
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        projects: [
          "subscriptions_holder", "t_coubs_initiator", "coub_smart_searcher",
          "kafka_message_producer", "kafka_message_consumer", "telegram_bot",
          "subscriptions_scheduler"
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: tests
        run: gradle ${{ matrix.projects }}:clean ${{ matrix.projects }}:test
